
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://oqlugmpkybpjehakjbls.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im9xbHVnbXBreWJwamVoYWtqYmxzIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDA0NjA3NjksImV4cCI6MjA1NjAzNjc2OX0.AGVgQq23QQZlVoe5Q9mwfljt6P6SSQ6cdJIL-IZ3kF4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);
